version: '3.1'

services:

  node:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./node_modules/.bin/nodemon --inspect=0.0.0.0:9229 ./bin/www | ./node_modules/.bin/bunyan
    ports:
      - "80:3000"
      - "9229:9229"
      - "9230:9230"
    volumes:
      - .:/home/node/app
      # bind-mounting these two files in will let you add packages during development without rebuilding
      # for example, to add bower to your app while developing, just install it inside the container
      # and then nodemon will restart. Your changes will last until you "docker-compose down" and will
      # be saved on host for next build
      # docker-compose exec node npm install --save bower
      - ./package.json:/home/node/app/package.json
      - ./package-lock.json:/home/node/app/package-lock.json
      - notused:/home/node/app/node_modules
    healthcheck:
      disable: true

volumes:
  notused: