version: '3.1'

services:

  node:
    build:
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_DB=instagram_dev
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres
    healthcheck:
      disable: true

  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d
      - ./postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=instagram_dev
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3
