CREATE TABLE `user` (
  `id` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `username` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `fullname` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `num_posts` int(11) NOT NULL,
  `num_followers` int(11) NOT NULL,
  `num_following` smallint(6) NOT NULL COMMENT 'limit is 7500',
  `average_likes` float(20,1) NOT NULL,
  `average_comments` float(20,1) NOT NULL,
  `is_private` tinyint(4) NOT NULL DEFAULT '0',
  `is_verified` tinyint(4) NOT NULL DEFAULT '0',
  `profile_pic_url` varchar(2083) COLLATE utf8_unicode_ci NOT NULL,
  `is_business_account` tinyint(4) NOT NULL DEFAULT '0',
  `business_category` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `business_email` varchar(320) COLLATE utf8_unicode_ci DEFAULT NULL,
  `business_phone` varchar(15) CHARACTER SET utf8 DEFAULT NULL,
  `business_address` json DEFAULT NULL,
  `csrf_token` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `country_code` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'e.g. "SG"',
  `language_code` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'e.g. "en"',
  `locale` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'e.g. "en_US"',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  UNIQUE KEY `username_UNIQUE` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `post` (
  `id` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `user_id` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `shortcode` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `url` varchar(2083) COLLATE utf8_unicode_ci NOT NULL,
  `num_likes` int(11) NOT NULL,
  `num_comments` mediumint(9) NOT NULL,
  `is_video` tinyint(4) NOT NULL DEFAULT '0',
  `video_view_count` int(11) DEFAULT NULL,
  `taken_at_time` datetime NOT NULL,
  `caption` text COLLATE utf8_unicode_ci,
  `location` json DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  UNIQUE KEY `user_id_UNIQUE` (`user_id`),
  UNIQUE KEY `shortcode_UNIQUE` (`shortcode`),
  CONSTRAINT `post_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;